const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const base = process.env.EXPLORER_URL || 'http://127.0.0.1:5011';

(async () => {
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, colorScheme: 'dark' });
    await context.route('**/api/**', (route) => route.fulfill({ json: [] }));
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    await page.goto(`${base}/users`);
    const control = page.getByRole('combobox', { name: 'Color theme' });
    const color = () => page.locator('body').evaluate((node) => getComputedStyle(node).color);
    assert.equal(await control.inputValue(), 'system');
    const dark = await color();
    await page.emulateMedia({ colorScheme: 'light' });
    const light = await color();
    assert.notEqual(light, dark);
    await control.selectOption('dark');
    assert.equal(await color(), dark);
    await page.reload();
    assert.equal(await control.inputValue(), 'dark');
    assert.equal(await color(), dark);
    const other = await context.newPage();
    await other.goto(`${base}/groups`);
    await control.selectOption('light');
    await other.waitForFunction(() => document.documentElement.dataset.theme === 'light');
    await page.emulateMedia({ colorScheme: 'dark' });
    assert.equal(await color(), light);
    await control.focus();
    await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().width > 207);
    assert.notEqual(await page.locator('.sidebar').evaluate((node) => getComputedStyle(node).boxShadow), 'none');
    if (process.env.THEME_SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.THEME_SCREENSHOT_DIR}/desktop-light.png` });
    await control.selectOption('system');
    assert.equal(await color(), dark);
    assert.equal(await page.evaluate(() => localStorage.getItem('powerview.theme')), null);
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await control.isVisible(), true);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    if (process.env.THEME_SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.THEME_SCREENSHOT_DIR}/mobile-dark.png` });
    await page.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage unavailable'); } }); });
    await page.reload();
    await control.selectOption('light');
    assert.equal(await color(), light);
    assert.deepEqual(errors, []);
    console.log('PASS: system theme, explicit overrides, persistence, cross-tab sync, keyboard focus, mobile layout and unavailable storage.');
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
