#!/usr/bin/env node
// Builds static/images/icons.svg from Microsoft Fluent UI System Icons (MIT).
// Usage: node tools/build-icons.mjs <path to @fluentui/svg-icons package>
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS = {
  download: 'arrow_download',
  'chevron-left': 'chevron_left',
  'chevron-right': 'chevron_right',
  key: 'key',
  domain: 'organization',
  globe: 'globe',
  folder: 'folder',
  ou: 'folder_list',
  user: 'person',
  group: 'people',
  computer: 'desktop',
  server: 'server',
  'service-account': 'person_settings',
  contact: 'contact_card',
  'foreign-principal': 'person_link',
  printer: 'print',
  'shared-folder': 'folder_link',
  object: 'cube',
  certificate: 'certificate',
  policy: 'document_settings',
  search: 'search',
  plus: 'add',
  minus: 'subtract',
  open: 'open',
  check: 'checkmark',
  info: 'info',
  unlock: 'lock_open',
  ban: 'prohibited',
  close: 'dismiss',
  refresh: 'arrow_clockwise',
  edit: 'edit',
  trash: 'delete',
  move: 'folder_arrow_right',
  copy: 'copy',
  'field-text': 'text_t',
  'field-class': 'tag',
  'field-date': 'calendar_ltr',
  filter: 'filter',
  'field-desc': 'text_description',
  alert: 'warning',
  empty: 'document_dismiss',
  dashboard: 'board',
  pathfinder: 'flow',
  explorer: 'text_bullet_list_tree',
  sun: 'weather_sunny',
  moon: 'weather_moon',
  more: 'more_horizontal',
};

const FILLED = ['explorer', 'dashboard', 'pathfinder', 'user', 'computer', 'group', 'globe', 'certificate', 'ou', 'policy', 'sun', 'moon'];

const source = process.argv[2];
if (!source) throw new Error('Pass the path to the @fluentui/svg-icons package.');
const version = JSON.parse(readFileSync(join(source, 'package.json'), 'utf8')).version;

function symbol(id, name, style = 'regular') {
  const file = [16, 20].map((size) => join(source, 'icons', `${name}_${size}_${style}.svg`)).find(existsSync);
  if (!file) throw new Error(`Fluent ${style} icon "${name}" (for "${id}") was not found.`);
  const svg = readFileSync(file, 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  return `  <symbol id="${id}" viewBox="${viewBox}" fill="currentColor">${body}</symbol>`;
}

const target = join(dirname(fileURLToPath(import.meta.url)), '..', 'static', 'images', 'icons.svg');
const lines = [
  '<svg xmlns="http://www.w3.org/2000/svg">',
  `  <!-- Fluent UI System Icons ${version}, Copyright (c) Microsoft Corporation, MIT License. Generated by tools/build-icons.mjs. -->`,
  ...Object.entries(ICONS).map(([id, name]) => symbol(id, name)),
  ...FILLED.map((id) => symbol(`${id}-filled`, ICONS[id], 'filled')),
  '</svg>',
];
writeFileSync(target, `${lines.join('\n')}\n`);
console.log(`Wrote ${Object.keys(ICONS).length} icons and ${FILLED.length} filled variants from Fluent UI System Icons ${version} to ${target}`);
